{% set name = "doccano" %}
{% set version = "1.5.0" %}

package:
  name: doccano
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cfabbfd9eb7a272fa699d6e9d076c72a2d312b67e3a933bd5e6d516495224776

build:
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:
    - '*/libc.musl-x86_64.so.1'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nodejs <14
  run:
    - nodejs <14

test:
  commands:
    - npm list -g {{ name }}

about:
  home: https://github.com/doccano/doccano
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open source text annotation tool for machine learning practitioner.
  doc_url: https://github.com/doccano/doccano
  dev_url: https://github.com/doccano/doccano

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
