{% set name = "doccano" %}
{% set version = "1.3.1" %}

package:
  name: doccano
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 430c8a16dba8a3f7bf34097e18c454ecbf887773166209eaa2ed0796b291f24e

build:
  number: 0
  noarch: python
  entry_points:
    - doccano = backend.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - apache-libcloud >=3.2.0
    - auto-labeling-pipeline >=0.1.12
    - celery >=5.0.5
    - colour >=0.1.5
    - conllu >=4.2.2
    - dj-database-url >=0.5.0
    - dj-rest-auth >=2.1.4
    - django-celery-results >=2.0.1
    - django-cors-headers >=3.5.0
    - django-drf-filepond >=0.3.0
    - django-filter >=2.4.0
    - django-rest-polymorphic >=0.1.9
    - djangorestframework-csv >=2.1.0
    - djangorestframework-xml >=2.0.0
    - drf-yasg >=1.20.0
    - environs >=9.2.0
    - furl >=2.1.0
    - gunicorn >=20.1.0
    - pyexcel >=0.6.6
    - pyexcel-xlsx >=0.6.0
    - python >=3.6
    - python-jose >=3.2.0
    - seqeval >=1.2.2
    - social-auth-app-django >=4.0.0
    - sqlalchemy >=1.4.7
    - whitenoise >=5.2.0

test:
  imports:
    - backend
    - backend.api
  commands:
    - doccano --help

about:
  home: https://github.com/doccano/doccano
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open source text annotation tool for machine learning practitioner.
  doc_url: https://github.com/doccano/doccano
  dev_url: https://github.com/doccano/doccano

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
