{% set name = "doccano" %}
{% set version = "1.6.2" %}

package:
  name: doccano
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5efcacbc2cc910c6caf6bcddbe74abae941d4e3b4ed7871b6510dd01cf7cc91f

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - npm list -g {{ name }}

about:
  home: https://github.com/doccano/doccano
  license: MIT
  license_file: LICENSE
  summary: Open source text annotation tool for machine learning practitioner.
  doc_url: https://github.com/doccano/doccano
  dev_url: https://github.com/doccano/doccano

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
    - xhochy
