{% set name = "doccano" %}
{% set version = "1.4.0" %}

package:
  name: doccano
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f6e0eebabe11d0118becf0dd0ee7fee4ee1b3013a124147c9c631bccc147a552
  patches:
    - rmv_drf_yasg.patch  # remove unneccesary dep drf_yasg in app/app/settings.py and app/app/urls.py

build:
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:
    - '*/libc.musl-x86_64.so.1'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nodejs <14
  run:
    - nodejs <14

test:
  commands:
    - npm list -g {{ name }}

about:
  home: https://github.com/doccano/doccano
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open source text annotation tool for machine learning practitioner.
  doc_url: https://github.com/doccano/doccano
  dev_url: https://github.com/doccano/doccano

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
